### ISSUE TITLE
JSON-LD and HTTP Pach

### ISSUE THREAD

**Issue by ghost** [juliangruber/multilevel-http#1]
Hey

JSON-LD is taking off as a way to do partial updates

HTTP PATH is an RFC but i don't think well supported yet.

It would be great to support JSON-LD for now.

There is a nodejs module for it.

Also this http server for level up wil likely grow to allow cap RIAK like management of many level up database ? I

**Comment by ghost** [comment]
Here is the implementation of JSON-LD
https://github.com/digitalbazaar/jsonld.js

Easy to integrate.

**Comment by juliangruber** [comment]
What exactly would you use JSON-LD for? What is HTTP PATH?

And for multiple servers: I like it being one process per DB, but you could easily write a wrapper that exports multiple databases:

``` js
var multilevel = require('multilevel-http')
var app = require('express')()

app.use('/db-1', multilevel.server('the-path'))

app.listen(3000)
```

Now under `localhost:3000/db-1/meta` you get the meta for db-1, etc.

**Comment by ghost** [comment]
HTTP PATCH

If you google JSON-LD its obvious how useful it is.
It allows partial updates.

On 1 February 2013 11:46, Julian Gruber notifications@github.com wrote:

> What exactly would you use JSON-LD for? What is HTTP PATH?
> 
> And for multiple servers: I like it being one process per DB, but you
> could easily write a wrapper that exports multiple databases:
> 
> var multilevel = require('multilevel-http')var app = require('express')()
> app.use('/db-1', multilevel.server('the-path'))
> app.listen(3000)
> 
> Now under localhost:3000/db-1/meta you get the meta for db-1, etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/juliangruber/multilevel-http/issues/1#issuecomment-12989190.

## 

Contact details:
+49 1573 693 8595 (germany)
+46 73 364 67 96 (sweden)
skype: gedw99

**Comment by juliangruber** [comment]
PATCH is only neat for updating JSON-data, and JSON isn't the default. What would happen if you perform a PATCH request to a string?

And I don't see why JSON-LD is necessary there, too. Why not just mongodb-style:

``` js
{
  set : { foo : 'bar' },
  del : ['other-key']
}
```

But most importantly, that's neither part of levelUP nor of leveldb, so I have no intend in supporting it.
