### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by raboof** [juliangruber/multilevel-http#16]
The README mentions multilevel-http does not support `events, for now` ;).

I'm really liking multilevel-http so far, and I wonder if you (still) consider a web-friendly way of listening for events in-scope for multilevel-http, or whether that'd fit better in a (companion) module?

Something like websockets, long-polling or EventSource come to mind, we could get inspiration from couchdb's `_changes` feed, too. I imagine you'd want to allow specifying some kind of (range?) filter.

**Comment by juliangruber** [comment]
You can use `multilevel`, which already works over websockets, and level-live-stream to send updates to the client :)
