### ISSUE TITLE
Feature request: support http auth

### ISSUE THREAD

**Issue by alessioalex** [juliangruber/multilevel-http#2]
If would be nice to add HTTP Auth support. Will work on this if I get the chance.

Note to self: don't forget about the CLI too

**Comment by juliangruber** [comment]
shouldn't

``` js
var db = multilevel.client('http://user:pw/localhost:5000/')
```

already work?

**Comment by alessioalex** [comment]
True, but I was thinking of making this built-in for the server, like pass a 'basicAuth' connect style function.

**Comment by juliangruber** [comment]
that should work:

``` js
var server = connect(connect.basicAuth(), multilevel.server)
```

since multilevel.server returns a http response handler

**Comment by alessioalex** [comment]
yes you're right. I'll include an example for this. thanks

**Comment by joyrexus** [comment]
@alessioalex Nice. Would love to see a working example of this in action.

**Comment by juliangruber** [comment]
@joyrexus instead of:

``` js
var server = multilevel.server(db);
```

this should work:

``` js
var server = connect(connect.basicAuth(options), multilevel.server(db))
```

**Comment by alessioalex** [comment]
@joyrexus there you go: https://github.com/alessioalex/multilevel-http/blob/master/examples/http-auth.js
