### ISSUE TITLE
ERROR: sudo npm install multilevel-http

### ISSUE THREAD

**Issue by MongoExpUser** [juliangruber/multilevel-http#22]
**I "sudo npm install multilevel-http"**

Then I encountered the  **errors below**. Based on the error logs, I think this problem is due to v8 engine version. Is there anyway I can install with current **Node Version (9.5.0)** & **NPM version 5.6.0**?

--------------------------------------------------------------------------------------
**root@localhost:/home/location# sudo npm install multilevel-http**

npm WARN deprecated connect@2.7.5: connect 2.x series is deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

> leveldown@0.1.4 install /home/location/node_modules/multilevel-http/node_modules/leveldown
> node-gyp rebuild

  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.0/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.0/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.0/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/async.o
In file included from ../src/database.h:13:0,
                 from ../src/async.cc:8:
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
../src/database.h:17:1: note: in expansion of macro ‘LD_SYMBOL’
 LD_SYMBOL ( option_createIfMissing , createIfMissing ); // for open()
 ^
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
../src/database.h:18:1: note: in expansion of macro ‘LD_SYMBOL’
 LD_SYMBOL ( option_errorIfExists   , errorIfExists   ); // for open()
 ^
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
../src/database.h:19:1: note: in expansion of macro ‘LD_SYMBOL’
 LD_SYMBOL ( option_compression     , compression     ); // for open()
 ^
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
../src/database.h:20:1: note: in expansion of macro ‘LD_SYMBOL’
 LD_SYMBOL ( option_cacheSize       , cacheSize       ); // for open() 
 ^
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
../src/database.h:21:1: note: in expansion of macro ‘LD_SYMBOL’
 LD_SYMBOL ( option_sync            , sync            ); // for put() and delete()
 ^
../src/leveldown.h:10:37: error: ‘NewSymbol’ is not a member of ‘v8::String’
     v8::Persistent<v8::String>::New(v8::String::NewSymbol(#key));
                                     ^
.,,,,,,,,,,,,,,,,,,,,,,,,

                 from ../src/async.cc:6:
/root/.node-gyp/9.5.0/include/node/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Value]’:
/root/.node-gyp/9.5.0/include/node/v8.h:644:25:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Value; M = v8::NonCopyablePersistentTraits<v8::Value>; T = v8::Value; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Value>]’
/root/.node-gyp/9.5.0/include/node/v8.h:9218:10:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Value; M2 = v8::NonCopyablePersistentTraits<v8::Value>; T = v8::Value; M = v8::NonCopyablePersistentTraits<v8::Value>]’
/root/.node-gyp/9.5.0/include/node/v8.h:710:9:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Value; M = v8::NonCopyablePersistentTraits<v8::Value>]’
../src/batch.h:28:20:   required from here
/root/.node-gyp/9.5.0/include/node/v8.h:162:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/root/.node-gyp/9.5.0/include/node/v8.h:648:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
/root/.node-gyp/9.5.0/include/node/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::Function]’:
/root/.node-gyp/9.5.0/include/node/v8.h:644:25:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::Function>]’
/root/.node-gyp/9.5.0/include/node/v8.h:9218:10:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::Function; M2 = v8::NonCopyablePersistentTraits<v8::Function>; T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
/root/.node-gyp/9.5.0/include/node/v8.h:710:9:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::Function; M = v8::NonCopyablePersistentTraits<v8::Function>]’
../src/async.cc:21:22:   required from here
/root/.node-gyp/9.5.0/include/node/v8.h:162:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                     ^
/root/.node-gyp/9.5.0/include/node/v8.h:648:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^
leveldown.target.mk:106: recipe for target 'Release/obj.target/leveldown/src/async.o' failed
make: *** [Release/obj.target/leveldown/src/async.o] Error 1
make: Leaving directory '/home/ecotert1/node_modules/multilevel-http/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.14-x86_64-linode94
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/location/node_modules/multilevel-http/node_modules/leveldown
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-13T03_49_31_861Z-debug.log

------------------------------------------------------------------------------------------------

**Comment by MongoExpUser** [comment]
Is this module still being maintained? If yes, are there distribute-able binaries.

**Comment by juliangruber** [comment]
looks like we need to update the leveldown dependency

**Comment by MongoExpUser** [comment]
juliangruber,
Thanks for the information. I will await the update.
